### ISSUE TITLE
Great extension ! Issue with quotes

### ISSUE THREAD

**Issue by thomasdarde** [wilfison/vscode-haml-all#2]
Hi !

Thank you for this great extension.

I only have one issue with format on save quotes, all simple quotes : ' are replaced with double quotes "
Is that something you are aware off ?

I can't find the linting rule that is responsible for this, is it UnecessaryInterpolation ?
https://github.com/sds/haml-lint/blob/main/config/default.yml

**Comment by wilfison** [comment]
Hello, this setting is taken from [rubocop Style/StringLiterals](https://docs.rubocop.org/rubocop/cops_style.html#stylestringliterals).

Check the current configuration of your project by running the command below inside the project:

```shell
rubocop --show-cops "Style/StringLiterals"
```

If the formatter is formatted differently than what was configured, send the output of the command above and the correct code snippet.

**Comment by thomasdarde** [comment]
Thank you very much !
Adding this to haml-lint does fix the issue :

```
  RuboCop:
    enabled: true
    # Users can ignore cops using this configuration instead of editing their rubocop configuration.
    # Mostly there for backward compatibility.
    ignored_cops: [Style/StringLiterals]
```

`"Renseigner l'email de l'admin"` was auto replaced by : `"Renseigner l"email de l'admin"` which was very annoying

**Comment by wilfison** [comment]
Check if you have a `.rubocop.yml` file in the root of your project and add or update the rule below:

```yml
Style/StringLiterals:
  enabled: true
  EnforcedStyle: double_quotes
```

After that you may need to reload the window for the new rules to be applied.
